{{- if eq .Values.mode "namespace" }}
{{- range .Values.ns }}
{{- if ne . $.Release.Namespace }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "kubernetes-chaos.name" $ }}-chaos-admin
  namespace: {{ . }}
  labels:
    {{- include "kubernetes-chaos.labels" $ | indent 4 }}
{{- end }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "kubernetes-chaos.name" $ }}-chaos-admin
  namespace: {{ . }}
  labels:
    {{- include "kubernetes-chaos.labels" $ | indent 4 }}
rules:

- apiGroups: [""]
  resources: ["pods/exec"]
  verbs: ["create", "get"]

- apiGroups: [""]
  resources: ["pods/log"]
  verbs: ["get"]

- apiGroups: [""]
  resources: ["pods/eviction"]
  verbs: ["create"]

- apiGroups: [""]
  resources: ["pods", "services","events","configmaps","secrets","replicationcontrollers"]
  verbs: ["create","delete","get","list","patch","update","deletecollection"]

- apiGroups: ["apps"]
  resources: ["daemonsets","replicasets","deployments","statefulsets"]
  verbs: ["create","delete","get","list","patch","update","deletecollection"]

- apiGroups: ["batch"]
  resources: ["jobs"]
  verbs: ["create","delete","get","list","patch","update","deletecollection"]

- apiGroups: ["litmuschaos.io"]
  resources: ["chaosengines","chaosexperiments","chaosresults"]
  verbs: ["create","delete","get","list","patch","update","deletecollection"]

- apiGroups: ["networking.k8s.io"]
  resources: ["networkpolicies"]
  verbs: ["create", "get", "list", "delete"]

- apiGroups: ["k8s.cni.cncf.io"]
  resources: ["network-attachment-definitions"]
  verbs: ["create","delete","get","list","patch","update","deletecollection"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "kubernetes-chaos.name" $ }}-chaos-admin
  namespace: {{ . }}
  labels:
    {{- include "kubernetes-chaos.labels" $ | indent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "kubernetes-chaos.name" $ }}-chaos-admin
subjects:
- kind: ServiceAccount
  name: {{ include "kubernetes-chaos.name" $ }}-chaos-admin
  namespace: {{ . }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "kubernetes-chaos.name" $ }}-chaos-admin-operator
  namespace: {{ . }}
  labels:
    {{- include "kubernetes-chaos.labels" $ | indent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "kubernetes-chaos.name" $ }}-chaos-admin
subjects:
- kind: ServiceAccount
  name: {{ include "kubernetes-chaos.name" $ }}-chaos-admin
  namespace: {{ $.Release.Namespace }}
{{- end }}
{{- end }}
